{{- if .Values.swaggerui.jsonPath }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "swagger-ui.fullname" . }}
  labels:
    app: {{ template "swagger-ui.name" . }}
    chart: {{ template "swagger-ui.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  conf.json: |-
    {{- .Files.Get .Values.swaggerui.jsonPath | nindent 4 -}}
{{- end }}
