{{- if .Values.secret.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  namespace: {{ .Values.secret.namespace }}
  labels:
    app: {{ include "dev-chatai.fullname" . }}
    argocd.argoproj.io/instance:  {{ include "dev-chatai.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secret.dockerConfigJson }}
{{- end }}
