apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-credentials
  namespace: logstash
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZGF0eC52biI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiI1NzNjOGQ5OS03MzVmLTQxNTItOTA4NS02NGI5MWY5OTVhMWUiLCJlbWFpbCI6Imh1bmcubGVAZGF0eC5jb20udm4iLCJhdXRoIjoiWVdSdGFXNDZOVGN6WXpoa09Ua3ROek0xWmkwME1UVXlMVGt3T0RVdE5qUmlPVEZtT1RrMVlURmwifX19
type: kubernetes.io/dockerconfigjson