apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: logstash
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5044
    nodePort: 31244
  selector:
    service: logstash
  sessionAffinity: None
