apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.headerless.type | default "ClusterIP" }}
  selector:
    {{- include "postgrest.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.serverPort | default 4000 }}
      protocol: TCP
      {{- if eq (lower .Values.headerless.type) "nodeport" }}
      nodePort: {{ .Values.headerless.nodePort }}
      {{- end }}
